export const mockMentors = [
    // Featured Mentor
    {
        name: 'Dr. Alena Kovalenko',
        title: 'Quantum Computing Researcher & Founder',
        expertise: ['Deep Tech', 'Quantum AI', 'Fundraising'],
        industry: 'Tech',
        country: 'Ukraine',
        bio: 'Pioneering the next wave of computation. A Forbes 30 Under 30 laureate, I guide young innovators turning complex science into viable businesses. Let\'s solve the unsolvable.',
        image: 'https://i.pravatar.cc/150?u=alena',
        availability: 'High',
        isFeatured: true,
    },
    // India
    {
        name: 'Rohan Verma',
        title: 'FinTech Entrepreneur & Angel Investor',
        expertise: ['FinTech', 'Blockchain', 'Angel Investing'],
        industry: 'Finance',
        country: 'India',
        bio: 'Scaled a digital payment gateway from zero to 100 million users. Now investing in and mentoring the next generation of financial disruptors.',
        image: 'https://i.pravatar.cc/150?u=rohan',
        availability: 'Medium',
    },
    // Tunisia
    {
        name: 'Yasmine Kchaou',
        title: 'AgriTech Innovator, Founder of GreenAtlas',
        expertise: ['Sustainability', 'AgriTech', 'IoT'],
        industry: 'Green Tech',
        country: 'Tunisia',
        bio: 'Using IoT and data to revolutionize farming in North Africa. Passionate about sustainable solutions and empowering rural entrepreneurs.',
        image: 'https://i.pravatar.cc/150?u=yasmine',
        availability: 'High',
    },
    // More Mentors
    {
        name: 'Ben Carter',
        title: 'CEO, EcoSolutions',
        expertise: ['Sustainability', 'Business Strategy', 'B2B Sales'],
        industry: 'Green Tech',
        country: 'USA',
        bio: 'Built a multi-million dollar company focused on sustainable packaging. Loves helping young founders navigate the B2B landscape.',
        image: 'https://i.pravatar.cc/150?u=ben',
        availability: 'Low',
    },
    {
        name: 'Chloe Nguyen',
        title: 'Lead Product Designer, FinConnect',
        expertise: ['UI/UX Design', 'Figma', 'User Research'],
        industry: 'FinTech',
        country: 'Vietnam',
        bio: 'Specializes in creating intuitive and beautiful user experiences for financial applications that people love to use.',
        image: 'https://i.pravatar.cc/150?u=chloe',
        availability: 'High',
    },
    {
        name: 'David Rodriguez',
        title: 'Growth Marketing Lead, SocialSphere',
        expertise: ['Marketing', 'SEO', 'Social Media'],
        industry: 'Social Media',
        country: 'Spain',
        bio: 'Expert in scaling user acquisition for consumer apps. Grew SocialSphere from 10k to 2M users in 18 months.',
        image: 'https://i.pravatar.cc/150?u=david',
        availability: 'Medium',
    },
    {
        name: 'Eva Mensah',
        title: 'Senior Software Engineer, HealthWell',
        expertise: ['Software Development', 'React', 'HealthTech'],
        industry: 'HealthTech',
        country: 'Ghana',
        bio: 'Building technology that improves healthcare access across Africa. Strong advocate for diversity and inclusion in tech.',
        image: 'https://i.pravatar.cc/150?u=eva',
        availability: 'High',
    },
    {
        name: 'Kenji Tanaka',
        title: 'Venture Capitalist, Innovate Capital',
        expertise: ['Venture Capital', 'Pitch Decks', 'Term Sheets'],
        industry: 'Finance',
        country: 'Japan',
        bio: 'Invests in the next generation of disruptive startups. I can help you understand the investor mindset and perfect your pitch.',
        image: 'https://i.pravatar.cc/150?u=kenji',
        availability: 'Low',
    },
    {
        name: 'Priya Singh',
        title: 'EdTech Founder, LearnSphere',
        expertise: ['EdTech', 'Product Management', 'SaaS'],
        industry: 'Education',
        country: 'India',
        bio: 'Passionate about making education accessible through technology. Bootstrapped LearnSphere to profitability.',
        image: 'https://i.pravatar.cc/150?u=priya',
        availability: 'Medium',
    },
    {
        name: 'Tariq Al-Jamil',
        title: 'Cybersecurity Analyst & Consultant',
        expertise: ['Cybersecurity', 'Python', 'Risk Assessment'],
        industry: 'Tech',
        country: 'UAE',
        bio: 'Protecting the digital world from threats. I help startups build secure and resilient products from day one.',
        image: 'https://i.pravatar.cc/150?u=tariq',
        availability: 'High',
    },
     {
        name: 'Sofia Volkov',
        title: 'Lead Game Developer, Quantum Leap',
        expertise: ['Game Development', 'Unity', 'C#'],
        industry: 'Gaming',
        country: 'Ukraine',
        bio: 'Crafting immersive worlds and interactive experiences. If you want to build the next big thing in gaming, let\'s talk.',
        image: 'https://i.pravatar.cc/150?u=sofia',
        availability: 'Medium',
    },
];